version: '3.7'
services:
  web:
    environment:
      - 'XDEBUG_CONFIG=idekey=gficoffee remote_host=${HOST_IP}'
      - 'PHP_IDE_CONFIG=serverName=gficoffee'
  db:
    ports:
      - '${DOCKER_DEVBOX_PORT_PREFIX}06:3306'
  mailcatcher:
    build:
      context: .docker
      dockerfile: mailcatcher/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}${DOCKER_DEVBOX_REGISTRY_REPOSITORY}/mailcatcher'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
