version: '2.2'
services:
  web:
    build:
      context: .docker
      dockerfile: web/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}${DOCKER_DEVBOX_REGISTRY_REPOSITORY}/web'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    volumes:
      - '${COMPOSE_PROJECT_DIR}:/var/www/html'
      - '${COMPOSE_PROJECT_DIR}/.docker/web/php-config.ini:/usr/local/etc/php/conf.d/php-config.ini'
      - 'web-composer-cache:/composer/cache'
      - '${COMPOSE_PROJECT_DIR}/.docker/web/apache.conf:/etc/apache2/sites-enabled/000-default.conf'
    user: '${USER_ID}:${GROUP_ID}'
  db:
    build:
      context: .docker
      dockerfile: db/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}${DOCKER_DEVBOX_REGISTRY_REPOSITORY}/db'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    environment:
      - MYSQL_ROOT_PASSWORD=gficoffee
      - MYSQL_DATABASE=gficoffee
      - MYSQL_USER=gficoffee
      - MYSQL_PASSWORD=gficoffee
    volumes:
      - '${COMPOSE_PROJECT_DIR}:/workdir'
      - 'db-data:/var/lib/mysql'
    user: '${USER_ID}:${GROUP_ID}'
  node:
    build:
      context: .docker
      dockerfile: node/Dockerfile
    image: '${DOCKER_DEVBOX_REGISTRY}${DOCKER_DEVBOX_REGISTRY_REPOSITORY}/node'
    init: true
    restart: '${DOCKER_DEVBOX_RESTART_POLICY}'
    volumes:
      - '${COMPOSE_PROJECT_DIR}:/app'
      - 'node-cache:/home/node/.cache'
      - 'node-npm-packages:/home/node/.npm-packages'
    user: '${USER_ID}:${GROUP_ID}'
volumes:
  web-composer-cache: null
  db-data: null
  node-cache: null
  node-npm-packages: null
