version: "2.2"
services:
  web:
    build:
      context: .docker
      dockerfile: php/Dockerfile
    image: ${DOCKER_DEVBOX_REGISTRY}gficoffee/web
    init: true
    restart: ${DOCKER_DEVBOX_RESTART_POLICY}
    volumes:
      - "${COMPOSE_PROJECT_DIR}:/var/www/html"
      - "${COMPOSE_PROJECT_DIR}/.docker/php/apache.conf:/etc/apache2/sites-enabled/000-default.conf"
      - "composer-cache:/composer/cache"
  db:
    build:
      context: .docker
      dockerfile: mysql/Dockerfile
    image: ${DOCKER_DEVBOX_REGISTRY}gficoffee/mysql
    init: true
    restart: ${DOCKER_DEVBOX_RESTART_POLICY}
    environment:
      - MYSQL_ROOT_PASSWORD=gficoffee
      - MYSQL_DATABASE=gficoffee
      - MYSQL_USER=gficoffee
      - MYSQL_PASSWORD=gficoffee
    volumes:
      - "${COMPOSE_PROJECT_DIR}:/workdir" # Mount this volume to help loading/exporting dumps
      - "mysql:/var/lib/mysql/"
  node:
    build:
      context: .docker
      dockerfile: node/Dockerfile
      args:
        GROUP_ID: "${GROUP_ID}"
        USER_ID: "${USER_ID}"
    image: ${DOCKER_DEVBOX_REGISTRY}gficoffee/node
    init: true
    volumes:
      - "${COMPOSE_PROJECT_DIR}:/app"
      - "node-cache:/home/node/.cache"
      - "node-npm-packages:/home/node/.npm-packages"
volumes:
  composer-cache:
  mysql:
  node-cache:
  node-npm-packages:
