minishlink_web_push:
  api_keys:                       # you should put api keys in your "app/config/parameters.yml" file
    GCM: ''
  VAPID:
    subject: 'https://gficoffee.test/'
    publicKey: 'BI5qCj0NdNvjDcBYTIXiNccdcP74Egtb3WxuaXrHIVCLdM-MwqPkLplHozlMsM3ioINQ6S_HAexCM0UqKMvaYmg'
    privateKey: 'MWCi4mx71gRWosOV6PSl1p4e6BdR0liAaP_rKwVg2Qg'
  ttl: 2419200                    # Time to Live of notifications in seconds
  urgency: ~                      # can be very-low / low / normal / high
  topic: ~                        # default identifier for your notifications
  timeout: 30                     # Timeout of each request in seconds
  automatic_padding: true         # pad messages automatically for better security (against more bandwith usage)